### ISSUE TITLE
Update all registered logos with trademarked logo

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/brand#33] opened 2019-02-01 18:39 UTC
@kathy-phet requested that all instances of the registered logo be replaced with a trademarked logo. 

I will update the asset files in this repo (phet and adapted from phet, since phet-io already uses TM) and png files and commit.

**Comment by amanda-phet** [comment] 2019-02-04 19:21
I updated the PhET logo assets and images, as well as the adapted-from-phet assets and images. 

@samreid can you please verify that I did everything correctly? 

Also, I skipped the logo-on-white.png under the PhET brand because it is identical to logo.png, since we made the change years ago to use one shade of yellow for all versions of the logo. Should we replace logo-on-white.png as well?

**Comment by samreid** [comment] 2019-02-04 19:34
I relabeled as "blocks-publication" since this affects every simulation.  For reference, "blocks-sim-publication" only blocks a single particular simulation.

**Comment by samreid** [comment] 2019-02-04 20:31
From slack:

Jonathan Olson [1:03 PM]
Is it ever expected to have a half-size progress bar?
Pasted image at 2019-02-04, 1:03 PM 
![image](https://user-images.githubusercontent.com/679486/52235382-23525000-2881-11e9-8956-1dc27e8219d0.png)



Steele Dalton [1:03 PM]
yea man

Sam Reid [1:04 PM]
That looks buggy

Steele Dalton [1:04 PM]
only when you want to load interactive, but not load simulations

Jonathan Olson [1:17 PM]
But yes, for some reason all of my progress bars are half-size, across browsers

Sam Reid [1:18 PM]
What OS?
Published sims too, or just requirejs?

Jonathan Olson [1:18 PM]
Also happened in a built sim

Chris Malley [1:18 PM]
Is that true for all sims on the PhET site, or just recently published sims?

Jonathan Olson [1:18 PM]
Windows 10
ahh checking

Kathryn Woessner [1:18 PM]
Just checked master and saw it
Not on published

Jonathan Olson [1:19 PM]
Published sims seem fine

Sam Reid [1:19 PM]
Rebooting in Windows, catch you later!

Chris Malley [1:20 PM]
I tried EFAC published and master on macOS+Chrome and both look OK to me.

Jonathan Olson [1:20 PM]
For everyone testing master, when did you last pull?

Kathryn Woessner [1:20 PM]
I was on a Win 10 device when I saw it
I pulled right before I tested

Chris Malley [1:21 PM]
I pulled ~9:30 am.  I’ll pull again.

Kathryn Woessner [1:21 PM]
I was on phettest btw
Mac OS 10.14 chrome saw it.

Jonathan Olson [1:23 PM]
Where is the code that handles the progress bar?

Chris Malley [1:23 PM]
After pull-all.sh, I now see the problem with EFAC master on macOS+Chrome. (edited) 

Sam Reid [1:23 PM]
Same problem here, running Chrome in Win 10 on phettest

Chris Malley [1:24 PM]
So something changed in the past few hours.
All browsers on macOS.

Sam Reid [1:26 PM]
I see the problem in Win/Chrome but not Mac/Chrome (both on phettest) (edited) 
The code is in joist/js/splash.js

Kathryn Woessner [1:27 PM]
I did see on Mac chrome

Chris Malley [1:27 PM]
With brand=adapted-from-phet, I see a _huge_ progress bar that goes off the edge of the screen.
I see many commits by @amanda in brand within the past hour.

Sam Reid [1:28 PM]
Oh wait, I know what it is.
There’s a blocks-publication issue recently assigned to me
With commits on the brand repo: https://github.com/phetsims/brand/issues/33

Chris, thanks for testing adapted-from-phet, that helped identify the problem
Investigating….

**Comment by samreid** [comment] 2019-02-04 20:37
It looks like the SVG viewBox approximately doubled in size.  The original dimensions were:

```
width="276px" height="132px" viewBox="114.001 114 276 132"
```

And the new dimensions are:

```
width="569.562px" height="269.505px" viewBox="0 0 569.562 269.505"
```

I'm not too familiar with SVG sizing, but if we can make sure the new SVG has the same dimensions as the prior SVG then it will make updating simpler.

**Comment by pixelzoom** [comment] 2019-02-04 20:40
I said:
> With brand=adapted-from-phet, I see a _huge_ progress bar that goes off the edge of the screen.

Here's a screenshot.

<img width="768" alt="screenshot_1018" src="https://user-images.githubusercontent.com/3046552/52235825-6fea5b00-2882-11e9-8d29-22ba20942015.png">

**Comment by samreid** [comment] 2019-02-04 20:44
@amanda-phet want to take it from here, or should I explore further?

**Comment by samreid** [comment] 2019-02-04 20:52
I tried loading the prior SVG file into illustrator, then I cut the "TM" out of the new file and pasted it into the old file, then used Illustrator "Save", and it seemed to work OK, but it would be best for @amanda-phet to take a look to make sure to get the "TM" in just the right size/position.

![image](https://user-images.githubusercontent.com/679486/52236396-f81d3000-2883-11e9-9999-4d468a49da1a.png)


<details>

```svg
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 16.0.4, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="273.173px" height="130.053px" viewBox="115.415 114.975 273.173 130.053"
	 enable-background="new 115.415 114.975 273.173 130.053" xml:space="preserve">
<g>
	<path fill="#6ACEF5" d="M149.438,139.104h-32c-1.104,0-2,0.896-2,2v79.987c0,1.104,0.896,2,2,2h17.66c1.104,0,2-0.896,2-2v-20.93
		c0-1.104,0.895-2,2-2h10.34c20.397,0,32.108-10.83,32.108-29.593C181.545,149.932,169.834,139.104,149.438,139.104z
		 M147.422,180.279h-8.326c-1.104,0-2-0.896-2-2v-19.547c0-1.105,0.896-2,2-2h8.326c9.568,0,12.59,6.547,12.59,11.838
		C160.012,174.111,156.99,180.279,147.422,180.279z"/>
	<path fill="#6ACEF5" d="M386.573,139.104h-122.81c-1.104,0-2,0.896-2,2v79.987c0,1.104,0.896,2,2,2h54.555c1.104,0,2-0.896,2-2
		v-13.754c0-1.104-0.896-2-2-2h-33.896c-0.553,0-1-0.446-1-1v-13.362c0-0.554,0.447-1,1-1h28.98c1.104,0,2-0.896,2-2v-13.75
		c0-1.104-0.896-2-2-2h-28.98c-0.553,0-1-0.449-1-1v-13.49c0-0.551,0.447-1,1-1l57.061,0.063c0.554,0,1,0.449,1,1v63.298
		c0,1.104,0.896,2,2,2h17.658c1.104,0,2-0.896,2-2v-63.298c0-0.551,0.445-1,1-1h21.436c1.104,0,2-0.896,2-2v-13.69
		C388.573,140,387.678,139.104,386.573,139.104z"/>
</g>
<g>
	<rect x="115.415" y="230.96" fill="#FFFFFF" width="3.581" height="13.896"/>
	<polygon fill="#FFFFFF" points="131.749,239.294 126.104,230.96 122.521,230.96 122.521,244.855 126.104,244.855 126.104,236.585 
		131.794,244.855 135.336,244.855 135.336,230.96 131.749,230.96 	"/>
	<polygon fill="#FFFFFF" points="137.818,234.21 141.818,234.21 141.818,244.855 145.4,244.855 145.4,234.21 149.445,234.21 
		149.445,230.96 137.818,230.96 	"/>
	<polygon fill="#FFFFFF" points="151.698,244.855 161.387,244.855 161.387,241.921 155.281,241.921 155.281,239.376 
		160.573,239.376 160.573,236.438 155.281,236.438 155.281,233.878 161.387,233.878 161.387,230.96 151.698,230.96 	"/>
	<path fill="#FFFFFF" d="M175.346,235.479c0-2.935-2.291-4.521-5.6-4.521h-5.482v13.896h3.586v-4.646h1.479l2.583,4.646h4
		l-3.354-5.187C174.163,239.146,175.346,237.771,175.346,235.479z M169.975,237.523h-2.125v-3.646h2.125
		c0.935,0,1.791,0.707,1.791,1.834C171.766,236.812,170.908,237.523,169.975,237.523z"/>
	<path fill="#FFFFFF" d="M183.25,230.96l-5.523,13.896h3.857l1.081-3.332h4.542l1.085,3.332h3.854l-5.522-13.896H183.25z
		 M183.52,238.876l1.42-4.312l1.394,4.312H183.52z"/>
	<path fill="#FFFFFF" d="M193.423,237.9c0,5.873,3.539,7.104,6.519,7.104c1.479,0,3.002-0.396,4.459-0.979v-3.104
		c-1.521,0.729-2.814,1.006-4.25,1.006c-1.646,0-3.146-0.729-3.146-4.021c0-3.295,1.501-4.021,3.146-4.021
		c1.435,0,2.729,0.271,4.25,1.002v-3.104c-1.457-0.582-2.979-0.98-4.459-0.98C196.962,230.794,193.423,232.021,193.423,237.9z"/>
	<polygon fill="#FFFFFF" points="206.302,234.21 210.301,234.21 210.301,244.855 213.887,244.855 213.887,234.21 217.928,234.21 
		217.928,230.96 206.302,230.96 	"/>
	<rect x="220.201" y="230.96" fill="#FFFFFF" width="3.585" height="13.896"/>
	<polygon fill="#FFFFFF" points="232.934,240.794 229.831,230.96 225.997,230.96 231.33,244.855 234.581,244.855 239.874,230.96 
		236.039,230.96 	"/>
	<polygon fill="#FFFFFF" points="242.023,244.855 251.71,244.855 251.71,241.921 245.605,241.921 245.605,239.376 250.896,239.376 
		250.896,236.438 245.605,236.438 245.605,233.878 251.71,233.878 251.71,230.96 242.023,230.96 	"/>
	<path fill="#FFFFFF" d="M261.622,234.646c0-1.541,1.229-2.373,3.44-2.373c1.414,0,2.561,0.438,3.332,0.875v-1.545
		c-0.896-0.438-2.064-0.83-3.48-0.83c-3.542,0-4.79,2-4.79,3.873c0,4.646,7.665,2.604,7.665,6.666c0,1.834-1.938,2.209-3.543,2.209
		c-1.893,0-3.184-0.562-3.998-1.104v1.621c0.979,0.522,2.334,0.979,4.104,0.979c3.104,0,4.938-1.397,4.938-3.713
		C269.291,236.001,261.622,237.689,261.622,234.646z"/>
	<rect x="272.378" y="230.958" fill="#FFFFFF" width="1.5" height="13.896"/>
	<polygon fill="#FFFFFF" points="283.879,238.023 279.107,230.96 277.484,230.96 277.484,244.855 278.984,244.855 278.984,233.419 
		283.879,240.501 288.796,233.419 288.796,244.855 290.296,244.855 290.296,230.96 288.674,230.96 	"/>
	<path fill="#FFFFFF" d="M303.761,239.232c0,2.979-1.353,4.416-4.144,4.416c-2.795,0-4.148-1.438-4.148-4.416v-8.271h-1.5v8.188
		c0,3.793,2.001,5.879,5.648,5.879c3.645,0,5.646-2.086,5.646-5.879v-8.188h-1.507L303.761,239.232L303.761,239.232z"/>
	<polygon fill="#FFFFFF" points="310.268,230.96 308.766,230.96 308.766,244.855 317.373,244.855 317.373,243.398 310.268,243.398 	
		"/>
	<path fill="#FFFFFF" d="M324.646,230.96l-5.545,13.896h1.623l1.672-4.33h6l1.664,4.33h1.604l-5.521-13.896H324.646z
		 M322.957,239.083l2.438-6.354l2.438,6.354H322.957z"/>
	<polygon fill="#FFFFFF" points="330.963,232.417 335.879,232.417 335.879,244.855 337.38,244.855 337.38,232.417 342.273,232.417 
		342.273,230.96 330.963,230.96 	"/>
	<rect x="344.55" y="230.958" fill="#FFFFFF" width="1.5" height="13.896"/>
	<path fill="#FFFFFF" d="M355.489,230.773c-4.271,0-6.438,2.395-6.438,7.127c0,4.727,2.167,7.123,6.438,7.123
		c4.293,0,6.46-2.396,6.46-7.123C361.949,233.167,359.782,230.773,355.489,230.773z M355.489,243.605
		c-3.417,0-4.938-1.748-4.938-5.705c0-3.939,1.521-5.713,4.938-5.713c3.438,0,4.96,1.771,4.96,5.713
		C360.449,241.857,358.93,243.605,355.489,243.605z"/>
	<polygon fill="#FFFFFF" points="374.895,242.666 366.602,230.96 364.893,230.96 364.893,244.855 366.393,244.855 366.393,233.148 
		374.704,244.855 376.395,244.855 376.395,230.96 374.895,230.96 	"/>
	<path fill="#FFFFFF" d="M380.916,234.646c0-1.541,1.229-2.373,3.438-2.373c1.418,0,2.563,0.438,3.34,0.875v-1.545
		c-0.896-0.438-2.063-0.83-3.479-0.83c-3.542,0-4.792,2-4.792,3.873c0,4.646,7.669,2.604,7.669,6.666
		c0,1.834-1.938,2.209-3.545,2.209c-1.896,0-3.188-0.562-4-1.104v1.621c0.979,0.522,2.336,0.979,4.104,0.979
		c3.104,0,4.938-1.397,4.938-3.713C388.585,236.001,380.916,237.689,380.916,234.646z"/>
</g>
<g>
	<path fill="#FEE105" d="M235.493,161.775c-0.8,2.488-1.558,5.004-2.244,7.567c-0.146,0.539-0.283,1.093-0.423,1.642
		c-6.436,27.812-2.946,45.998-1.735,51.918c0.281,0.119,0.58,0.188,0.882,0.188h16.332c1.104,0,2-0.896,2-2v-35.02
		C250.305,174.464,245.052,165.753,235.493,161.775z"/>
	<path fill="#FEE105" d="M211.771,160.132v-21.799c0-1.104-0.896-2-2-2h-17.658c-1.104,0-2,0.896-2,2v82.758c0,1.104,0.896,2,2,2
		h11.109c0.504,0,0.99-0.19,1.394-0.493c3.131-25.072,12.497-46.886,21.75-63.033c-1.255-0.119-2.548-0.188-3.892-0.188
		C219.075,159.376,214.793,159.626,211.771,160.132z"/>
	<polygon fill="#FEE105" points="221.92,131.225 234.307,135.705 250.253,122.427 237.982,136.955 251.236,141.626 256.021,114.975 
			"/>
	<polygon fill="#FEE105" points="238.004,139.546 238.312,146.48 243.254,141.541 	"/>
</g>
<g>
	<path fill="#6ACEF5" d="M370.984,222.725v-7.498h-2.799v-1.003h6.736v1.003h-2.812v7.498H370.984z"/>
	<path fill="#6ACEF5" d="M376.04,222.725v-8.501h1.694l2.01,6.018c0.187,0.562,0.323,0.979,0.406,1.26
		c0.098-0.311,0.248-0.764,0.452-1.362l2.035-5.915h1.513v8.501h-1.084v-7.113l-2.47,7.113h-1.015l-2.457-7.235v7.235H376.04z"/>
</g>
</svg>
```

</details>

UPDATE: I remembered I also needed to update the artboard bounds.

**Comment by samreid** [comment] 2019-02-04 22:18
I confirmed the PNGs and PhET-brand SVG have the same dimensions.  The PhET-brand SVG has a different viewbox, but hopefully that is not a problem.  

However, the Adapted from PhET SVG has different dimensions.  The original dimensions were:
```
width="273px" height="130px"
```
and the new dimensions are:

```
width="276px" height="132px"
```

Can this be corrected?

**Comment by samreid** [comment] 2019-02-04 22:22
> Should we replace logo-on-white.png as well?

Yes please.

Also, I noticed that the "TM" exceeds the rightmost bounds of the top of the "T" for the PNG, but not for the SVG.  The "TM" is proportionately much smaller in the SVG.  Is that by design?

**Comment by amanda-phet** [comment] 2019-02-04 22:24
In the previous comment the dimensions said 276x132 so I assumed it was the same for both logos. 

>Also, I noticed that the "TM" exceeds the rightmost bounds of the top of the "T" for the PNG, but not for the SVG. 

Can you show me what you mean? 

> The "TM" is proportionately much smaller in the SVG. Is that by design?

Yes. The TM (and previously the (R)) is smaller in large logos, and larger in small logos. The TM should be the same width as the (R) for all logos.

**Comment by samreid** [comment] 2019-02-04 22:28
> Can you show me what you mean?

![image](https://user-images.githubusercontent.com/679486/52241499-1e959800-2891-11e9-9410-55b9b3a2bb85.png)

**Comment by samreid** [comment] 2019-02-04 22:30
Looks like this is not a problem for the PhET-brand one.  I used a paint fill to see where the "feathered edges" of the T and TM extend to.

![image](https://user-images.githubusercontent.com/679486/52241735-bb583580-2891-11e9-9cdb-315a507518f6.png)

**Comment by pixelzoom** [comment] 2019-02-07 03:43
Is this being done because PhET trademarks are not registered? 

If that's the case... Does this paragraph need to change at https://phet.colorado.edu/en/licensing/html#agreement-III ?
> III. PHET NAME AND LOGO TRADEMARK
> 
> The PhET name and PhET logo are registered trademarks of The Regents of the University of Colorado, a body corporate.

**Comment by pixelzoom** [comment] 2019-02-07 03:45
Hmmm... This website indicates that PhET's logo is a registered trademark (word mark),  with registration #4572418. https://trademarks.justia.com/861/62/phet-86162666.html

**Comment by kathy-phet** [comment] 2019-02-07 04:23
We are registered. It’s because we are international. Registration is by country.

Google uses TM for that reason, even though they are also registered in a number of countries but not every country.

Kathy
Sent from my iPhone

On Feb 6, 2019, at 8:45 PM, Chris Malley <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmmm... This website indicates that PhET's logo is a registered trademark (work mark), with registration #4572418. https://trademarks.justia.com/861/62/phet-86162666.html

**Comment by pixelzoom** [comment] 2019-02-07 04:24
Thanks for the clarification.

**Comment by jessegreenberg** [comment] 2019-02-07 21:10
Discussed during dev meeting and reviewed, this doesn't need to block publication and changes only involved images and SVG assets.

**Comment by jessegreenberg** [comment] 2019-02-07 21:11
Before going through maintenance releases, @kathy-phet and @amanda-phet should review the changes.

#34 will cover the maintenance releases.

**Comment by amanda-phet** [comment] 2019-02-08 18:41
@samreid said 
>Also, I noticed that the "TM" exceeds the rightmost bounds of the top of the "T" for the PNG, but not for the SVG. The "TM" is proportionately much smaller in the SVG. Is that by design? 

This was the case in the original logo, and the "R" also exceeded the bounds. I replaced the R with TM without noticing it in the original, so I'm updating all of the adapted-from-PhET assets again to look better. @samreid it would be great if you could confirm that the newest logos look better.

**Comment by samreid** [comment] 2019-02-10 04:50
The alignment in the adapted from PhET logo seems better to me:

![image](https://user-images.githubusercontent.com/679486/52529725-47b09100-2cb4-11e9-8f9b-1bf6a64a9595.png)

However, when I loaded the adapted-from-phet SVG file in illustrator and fit the artboard to the art bounds, I noticed there was an extra copy:

![image](https://user-images.githubusercontent.com/679486/52529732-87777880-2cb4-11e9-9dfd-f76ae1258789.png)

A similar issue is that the SVG file went from 28 lines of code to 125 lines of code, this further supports the hypothesis that there is more "hidden geometry" in this file that should be cleaned up before we begin maintenance releases in #34.

**Comment by amanda-phet** [comment] 2019-02-11 16:12
>However, when I loaded the adapted-from-phet SVG file in illustrator and fit the artboard to the art bounds, I noticed there was an extra copy:

You're right @samreid , I made a copy because I converted the text to outlines and didn't delete the text version. Should be fixed now.

**Comment by samreid** [comment] 2019-02-11 16:26
Thanks @amanda-phet, that looks fixed.

**Comment by ariel-phet** [comment] 2019-02-12 04:44
@samreid this all looks pretty good, but there is one very minor polish (which also exists on published sims)

The "kabob" is not quite aligned with the logo (I added white lines for reference). It looks like a small tweak to spacing or such might fix this issue. 

![menu](https://user-images.githubusercontent.com/4051174/52612256-297a9a80-2e46-11e9-88f9-8b76dd6bdd7e.PNG)

**Comment by samreid** [comment] 2019-02-12 15:07
I adjusted the location of the KebabMenuIcon and adjusted the spacing to align with the logo:

![image](https://user-images.githubusercontent.com/679486/52644985-21017e80-2e9d-11e9-8db4-4dc131e58e85.png)

In context:

![image](https://user-images.githubusercontent.com/679486/52645033-34ace500-2e9d-11e9-9c29-d03a0c13af90.png)

I'll commit this, but I'm happy to make further adjustments as desired.

**Comment by ariel-phet** [comment] 2019-02-12 17:45
@samreid I checked on master and the spacing and such looks good. However, when I compared to a published sim it looks like the height of the navbar changed slightly. On a published sim (EFAC for instance) the Navbar on master looks like the black band is about a pixel or so shorter. I don't think that is necessarily a problem, but I am curious if that change was intentional?

**Comment by samreid** [comment] 2019-02-12 18:03
I didn't intentionally change the navbar height.  To investigate further, I launched:
https://phet.colorado.edu/sims/html/energy-forms-and-changes/latest/energy-forms-and-changes_en.html
and
http://localhost/energy-forms-and-changes/energy-forms-and-changes_en.html?brand=phet&ea

in adjacent tabs in Mac Chrome and Mac Firefox and CMD+OPT+ARROW to flip back and forth and I couldn't distinguish between the navbar height.  The only apparent change in these tests was the change in the logo and kebab, and it looks like the logo moved about 1px to the left.

Would you like me to investigate further?  I could run the same test on Windows.  What platform did you observe the difference on?  Were you using phettest, or a local pull?

**Comment by ariel-phet** [comment] 2019-02-12 18:10
@samreid I did a local pull, and was testing on Chrome Win 7, flipping back and forth. I put a pixel ruler on the screen to see the difference, it was about 1 pixel.

**Comment by samreid** [comment] 2019-02-12 18:33
I used Windows 10 Pro Chrome to compare phettest (with pulled joist) to published EFAC and again the navigation bar sizes were indistinguishable.  I recommend assigning another developer to investigate and see if they can reproduce the problem and isolate the cause.

**Comment by ariel-phet** [comment] 2019-02-13 18:51
@samreid checked on Win 7 FF, issue does not appear

Checked on Win 10 FF and Chrome, issue does not appear

Since it is only a pixel on Win 7 Chrome, and pretty subtle I think we can proceed.

**Comment by samreid** [comment] 2019-02-13 23:21
For this issue, I double checked that the changed PNG and SVG files have the correct width and height, and the new ones have "TM" instead of "R".  @ariel-phet signed off as a designer we revised the size of the kebab menu to match the logo.  The only thing I'm aware of that we may want to discuss or improve for this issue is for the PhET brand logo SVG, which is shown for the splash screen, the "TM" isn't centered or apparently aligned with anything and I'm not sure how its size was determined.  I don't know if this is by design or not:

![image](https://user-images.githubusercontent.com/679486/52750999-2e0c9380-2fab-11e9-8299-c0455b81ebdd.png)

@ariel-phet and @amanda-phet can you comment on that before we begin maintenance releases in https://github.com/phetsims/brand/issues/34 ?

**Comment by samreid** [comment] 2019-02-13 23:26
One more thing I noticed is that when loading this SVG in illustrator the artboard doesn't align with the artwork.

![image](https://user-images.githubusercontent.com/679486/52751227-02d67400-2fac-11e9-95d3-784d52880520.png)

I do not know enough about SVG to know what's causing this problem, but I should also note this is not a new problem, our old SVG has been off-centered like this for ages.  We may wish to investigate if we think browsers may update and cause problems for this in the future, but as far as I know we've been safe up until now.

**Comment by ariel-phet** [comment] 2019-02-14 02:39
@samreid the Splash screen logo should just match the navbar logo (in terms of size and placement of the TM). If you need a new asset for this, I am sure @amanda-phet will be able to oblige.

**Comment by amanda-phet** [comment] 2019-02-14 03:13
The splash screen does not match the navbar because of its size. Kathy hasn't defined a hard and fast cutoff for when to use the various sizes, but the size and placement of the registered symbol was determined years ago. For "medium-large" versions of the PhET logo, the TM (previously the R) should be the size you see in the splash screen. For "small" versions of the PhET logo (when you would definitely not include the Interactive Simulations text), the TM is proportionally larger. Ideally the *actual* size of the TM is similar in both versions. 

I will investigate the artboard issue. My guess is the issue persisted because the same asset was used to make the new splash.svg, as all we did was replace the R with TM (same for the other strange issue in https://github.com/phetsims/brand/issues/33#issuecomment-460436862 above).

**Comment by amanda-phet** [comment] 2019-02-14 03:18
I moved the artwork to the center of the artboard, committed it (https://github.com/phetsims/brand/commit/df790422b9249fc19d7b77a0afecdeb4b28cc7cc) and downloaded it again. Seems to be fixed.

**Comment by samreid** [comment] 2019-02-14 03:59
> Kathy hasn't defined a hard and fast cutoff for when to use the various sizes, but the size and placement of the registered symbol was determined years ago.

Sounds OK to me.  Also, can you comment on why the TM isn't centered or right aligned?  I'm not sure whether that would look better at all though.  Perhaps it was just to match the style from years ago.

> Ideally the _actual_ size of the TM is similar in both versions.

Perhaps it doesn't matter too much because you can't see both at the same time, but I snapshotted both from master and saw that they are off by a factor of around 2:

![image](https://user-images.githubusercontent.com/679486/52761772-054bc480-2fd2-11e9-9acc-9cbd4c838fe8.png)

However, we don't have much room to expand the small TM and shrinking the large TM would make it really tiny.  So I'm not sure what should be done, if anything.

> I moved the artwork to the center of the artboard,

I confirmed the artboard bounds looks fixed, thanks!

**Comment by amanda-phet** [comment] 2019-02-14 17:19
>can you comment on why the TM isn't centered or right aligned?

When we settled on the location for the R, I recall doing different things to align it and play with the size, and this location looked the most natural. We compared with other popular logos out there, and they seemed to have a similar location- they appear to either be nestled in a cozy spot or were adjacent to the logo. When it was aligned with the right edge of PhET, it started to look like a period- but perhaps since the TM is not in a circle it could be reconsidered. If you think the location should be tweaked, please bring it up with @kathy-phet .

**Comment by ariel-phet** [comment] 2019-02-14 17:22
Agreed with @amanda-phet, I have no strong preference on how the splash screen looks, if you think it should be tweaked, discuss with @kathy-phet. If not, please move forward.

**Comment by samreid** [comment] 2019-02-14 17:54
Thanks for the additional discussion.  I'm not aware of anything else that remains to do for this issue before maintenance releases begin in https://github.com/phetsims/brand/issues/34.  Please correct me and reopen if I'm wrong.  @amanda-phet and @ariel-phet thanks for your help here.

**Closed as completed by samreid** 2019-02-14 17:54 UTC
Labels: type:licensing

**Comment by kathy-phet** [comment] 2019-02-25 18:06
@samreid , @ariel-phet , @amanda-phet - I looked on phettest, and the new TM trademarks look good there. I found one other issue that needs to be addressed as part of maintenance, so will start a new issue about that.
